# Generated by Django 4.1.5 on 2023-03-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_room_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
