# Generated by Django 4.1.5 on 2023-03-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_room_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='trending',
        ),
    ]
