# Generated by Django 4.1.5 on 2023-03-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_name_room_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='trending',
            new_name='name',
        ),
    ]
